featureFlags:
  flags:
  - flag:
      name: featureflagvalue2
      identifier: featureflagvalue2
      description: ""
      permanent: true
      spec:
        type: boolean
        default:
          onVariation: "false"
          offVariation: "false"
        variations:
        - identifier: "true"
          value: "true"
        - identifier: "false"
          value: "false"
      environments:
      - identifier: python
        default:
          onVariation: "false"
          offVariation: "false"
        state: "off"
  - flag:
      name: python_djnago
      identifier: python_djnago
      description: ""
      permanent: false
      spec:
        type: boolean
        default:
          onVariation: "true"
          offVariation: "false"
        variations:
        - identifier: "true"
          value: "true"
        - identifier: "false"
          value: "false"
      environments:
      - identifier: python
        default:
          onVariation: "true"
          offVariation: "false"
        state: "off"
        targetRules:
        - targets:
          - identifier: abhi
          variation: "true"
  projectIdentifier: python_djnago
  orgIdentifier: default
